## step0 of the apm bug-lab
services:
  ddtimer:
#    platform: linux/amd64
#    image: lancel00zz/ddtimer:latest
    image: ddtimer:latest
#    pull_policy: always
    ports:
      - "5056:5050"
    restart: unless-stopped      
    volumes:
    ## it loads dev environment folders inside the container - so it is a direct and live link to them
      - ./:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://ddtimer:ddtimerpassword@db:5432/ddtimerdb
    labels:
      com.datadoghq.ad.logs: '[{"source": "docker"}]'
    networks:
      - ddtimer-network



  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ddtimerdb
      POSTGRES_USER: ddtimer
      POSTGRES_PASSWORD: ddtimerpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ddtimer-network


networks:
  ddtimer-network:
    driver: bridge

volumes:
  db_data: