## this creates a docker container based on the dockerhub image below.
## run it in chrome localhost:5050 or <IP_address>:5050 (better for QR codes)
## to build it:
## docker compose -f docker-compose.yml -p facilitator-prod up
## or in verbose mode (in terminal with an ongoing console):
## docker compose -f docker-compose.yml -p facilitator-prod up -d
## ------------------- end ----------------
services:
  ddtimer:
    platform: linux/amd64
    image: lancel00zz/ddtimer:latest
    pull_policy: always
    ports:
      - "5050:5050"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - DD_ENV=prod-local
      - DD_SERVICE=ddtimer
      - DD_VERSION=4.8
    labels:
      com.datadoghq.ad.logs: '[{"source": "docker"}]'
    networks:
      - ddtimer-network

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    platform: linux/amd64
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_APM_ENABLED=false
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_CONTAINER_EXCLUDE=name:datadog-agent
      - DD_HOSTNAME=ddtimer-agent-prod-local
      - DD_ENV=prod-local
      - DD_SERVICE=ddtimer
      - DD_VERSION=4.8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: unless-stopped
    networks:
      - ddtimer-network

networks:
  ddtimer-network:
    driver: bridge
