FROM python:3.11-slim

WORKDIR /app

RUN pip install flask

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app       /app/app
COPY config    /app/config
COPY run.py    /app/run.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=5050"]