
services:
  facilitator:
    platform: linux/amd64
    image: lancel00zz/facilitator-timer-app:4.0
    environment:
      - HOST_IP=${HOST_IP}
    ports:
      - "5050:5050"
    restart: unless-stopped
