## HOST_IP=$(ipconfig getifaddr en0) docker compose -f docker-compose.dev.yml -p facilitator-dev up -d
## ------------------- end ----------------
services:
  facilitator:
    platform: linux/amd64
    image: lancel00zz/facilitator-timer-app:4.0
    ports:
      - "5056:5000"
    volumes:
    ## it loads my dev environment folders inside the container - so it is a direct and live link to them
      - ./app:/app/app
      - ./config:/app/config
    environment:
      - HOST_IP=${HOST_IP}
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000 --reload